name: Android CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        jdk-version: [11]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk-version }}
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
